# Generated by Django 5.0.3 on 2024-05-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
