# Generated by Django 5.0.3 on 2024-05-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_job_person_movie_moviereview_moviecredit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
