# Generated by Django 5.0.3 on 2024-05-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
